### ISSUE TITLE
Trouble resetting traffic

### ISSUE THREAD

**Issue by Nipoto** [alireza0/x-ui#18]
hi
When an active subcategory account runs out of traffic, it will be deactivated, but when we reset the traffic, it will not be activated again. You must edit the main account and increase or decrease the number of that sub-account to reactivate it

**Comment by alireza0** [comment]
Hello,
Thank you for this report. It is fixed and will be available in next release soon.

**Comment by alirezarm78** [comment]
Still doesn't work reset traffic
Even i removed traffic limitation and it does not connect even with that and only way to back client is restart service.

**Comment by alireza0** [comment]
> Still doesn't work reset traffic Even i removed traffic limitation and it does not connect even with that and only way to back client is restart service.

@alirezarm78 Please upgrade to 0.3.1 to solve the problem.
It was forgotten to add auto-restart after change in clients

**Comment by r0zbeh** [comment]
hi thanks for you beautiful job :)
when reset traffic in control panel its don`t update immediately , and user should refresh the page !

**Comment by alireza0** [comment]
Hi @r0zbeh,

In the latest release 0.3.2, it is optimized in [Optimize Client-traffic-reset](https://github.com/alireza0/x-ui/commit/9e398aaa65446d574a90b4dce40c75f1b811d769) and will always reload all the data from database after traffic reset.

If you just have it updated, please make sure that you did hard-reload the webpage once or/and clear the cache in your browser.
