### ISSUE TITLE
Bug in deleting the client

### ISSUE THREAD

**Issue by Nipoto** [alireza0/x-ui#20]
hi
The new "delete client" feature has a bug and set decryption value to null. 
I had to edit the database manually to fix the problem.

![1](https://user-images.githubusercontent.com/3000646/221002827-ac6e1382-6131-494e-b897-0951ee845d09.png)
![2](https://user-images.githubusercontent.com/3000646/221002814-cf750008-e040-49b4-9893-81435410bc26.png)

**Comment by alireza0** [comment]
Thank you for this report.
It seems a bug in modules or go 1.20 happened!
Only fingerprint enabled protocols (trojan/vmess) has this issue.
It is now fixed. I have updated the last version.
Please update it

**Comment by Nipoto** [comment]
thank you 

Based on the code changes, the problem seems to be solved, but it still exists
`Xray 1.7.5 (Xray, Penetrates Everything.) Custom (go1.20 linux/amd64) A unified platform for anti-censorship. 2023/02/24 09:52:44 [Info] infra/conf/serial: Reading config: bin/config.json Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: VLESS settings: please add/set "decryption":"none" to every settings`

p.s: I updated an hour ago and then restarted

**Comment by alireza0** [comment]
Unfortunately it has changed a static part of settings. I will edit this version to use Hard-Coded static value for `decryption`. Then you can fix it by edit and save the affected VLESS inbound once.

**Comment by alireza0** [comment]
Please update and check.
[DIFF](https://github.com/alireza0/x-ui/commit/4843c936086a5f273b4ef29aefaa8f1cd3d82684#diff-b5ef5f7bdd4bc564ca919c23529956b3402c3065543fbe2f773088b6893cb467R1419)

**Comment by Nipoto** [comment]
fixed
thank you

**Comment by Nipoto** [comment]
Unfortunately, there is still a problem
On an active port that I tested now, it gave an error again and there was no solution except editing the database

**Comment by alireza0** [comment]
Sorry to here that!
Did you update the x-ui?
Did you open the edit modal and save it?
Could you please send me the details about this error?

**Comment by Nipoto** [comment]
Yes, I had done the necessary updates

`Xray 1.7.5 (Xray, Penetrates Everything.) Custom (go1.20 linux/amd64) A unified platform for anti-censorship. 2023/02/25 09:29:31 [Info] infra/conf/serial: Reading config: bin/config.json Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: VLESS settings: please add/set "decryption":"none" to every settings`

**The interesting point is that: i fixing the problem manually, but after creating the subcategory account, the error appeared again**

**Comment by alireza0** [comment]
I did all these tests. But instead of new version, I removed the last version and replace fixed version.
Please use `x-ui update` again.

**Comment by Nipoto** [comment]
I ran the following commands again : 

`x-ui update`
`x-ui restart`

And I deleted a subUser


Result :
![Untitled](https://user-images.githubusercontent.com/3000646/221359728-08f8f742-d761-4b06-ad9c-5cec27aef4a3.png)

**Comment by alireza0** [comment]
Great!
Instead of removing sub-user (client) just edit the inbound and hit the `Revise` button to save the inbound in db correctly.

**Comment by Nipoto** [comment]
I did the same several times. Both before and after the problem. It did not work

**Comment by alireza0** [comment]
Something is wrong here.
Others tried and fixed the db by this way:
https://github.com/alireza0/x-ui/issues/25#issuecomment-1445041215

Please:
1. Check if you do this edit-save process for all affected VLess inbounds.
2. Check if you allow `x-ui update` to download and reinstall the package from github.
3. Check manually in db if the problem is fixed by edit-save


If everything is okay then please send me the server details such as os release and sample config

**Comment by Nipoto** [comment]
Thanks for the time you left. 
I had done all the steps before sending a message in issue. 
Every 3 steps. 

But unfortunately it didn't work for me.

**Comment by Nipoto** [comment]
Ubuntu 22
Finland ~ Hetzner
2 VCPU
2 GB RAM
40 GB DISK LOCAL

====
config:
Vless > 443 > WS > TLS

**Comment by alireza0** [comment]
It is normal!
So, I decided to revert back to version 0.2.4 as the last stable one, till fixing all these bugs.
I need time to work on new features.

Please re install it to have automatic downgrade.
Sorry for these problems

**Comment by Nipoto** [comment]
thank you

does this line need to be changed?
`web/assets/js/model/xray.js : 1427`

**Comment by alireza0** [comment]
Actually, I have fixed it [here](https://github.com/alireza0/x-ui/blob/main/web/assets/js/model/xray.js#L1402).
When it creates new inbound ( for ex. when you save the edited inbound ) then it will not use current `decryption` value and will change it to `none` by force.

**Comment by alireza0** [comment]
New release is ready with lots of fixes.
Please check and feedback.

Thanks again

**Comment by Nipoto** [comment]
Thanks for your efforts.
I will definitely check

**Comment by Nipoto** [comment]
I tested and the problem is solved
thank you

@alireza0

**Comment by alireza0** [comment]
Thanks again for report and contributing @Nipoto
